# fly.toml app configuration file generated for server-ln on 2023-12-23T04:50:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-ln"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
